auth:
  token:
    encryptedSecret: #TODO: generate sealed secret
mongodb:
  encryptedUri: AgAh/eB1jrBo9apI+AuWEBaZBWg4o4YTP57Lb9PwjtzGHmF0X2fpNSv4lCAZlxJbZoiaYTBkyySD4zye57QFLN6O1+KnVk/DLytEHIB448QsQhw1zuDIf8E7xSOC+7Q5etacnk3F/5fZdDRe+1pzj61I8tyVlzRip2cDJS5YmMSoOQuNCFLoUYsuMoCC1Aj3jroXqYzQKpOfw06aa3KC90nc/2YGcnEQFx5i2xsFGVTZ+K7hkTP275I/B+vKO5zcrRj+NnZKLF0AohzO2SCjGMAAzOowoW1aUSzHucrYfUpQsrR4ZUvmeow5ceHidDrEdM3WYG/h5Az8VGudCiIxgCvWumf9ejwknwCH8xvWM3l1hfw7+VfU7FWvC7K1kiqTEarNgqfU7qnR2X4KVU8iXN3A+2M8ZKxr48WA3jZUIJaZ31MVLVLE9jMQ1GsJ01ogwDMARt/1eZoPJcHOk++c/aGOAfUN9Ps/IojASiSyRlViCLMvzeYKNuPa6lONjQDX+1As7VNtXNzEv2fkSkLiq0g1zWCNt6jy8OEJEBxjjPPKrQ/qXnWSyDEHkUc+RLJu1k7Cp6uiDPPY1Dy0FVsHuteZSz5+EMLkbJKkrJQvJL516cGnw8GXLYHEgFnVdl3p+doE0kVMMeKQI5Wo3Rku2vvoqke6m3SA6cHoHK3OZu9AVQEfmGm7ucfnqgqCgBxgUrTkNxE3DNAPRd9HMwiDtEY0b0zaa3hA3jYL/frGB2EYRK+ZRpdWIwSLihxu0tdxD7re1DovA5WT2mVwuQXxFd2qQ/H6DMupJ0y2RNI6kglNFA==
mistral:
  encryptedToken: #TODO: generate sealed secret
ingress:
  host: scr.g3.minikube