apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smm-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    keycloakClientSecret: {{ .Values.auth.token.encryptedSecret }}
  template:
    metadata:
      name: smm-client-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
