apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-app-movie.fullname" . }}
  labels:
    app: {{ include "springboot-app-movie.name" . }}
    version: {{ include "springboot-app-movie.name" . }}-{{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "springboot-app-movie.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "springboot-app-movie.name" . }}
        version: {{ include "springboot-app-movie.name" . }}-{{ .Values.image.tag }}
    spec:
      containers:
          - name: {{ include "springboot-app-movie.name" . }}
            version: {{ include "springboot-app-movie.name" . }}-{{ .Values.image.tag }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.service.port }}
            envFrom:
              - configMapRef:
                  name: service-movie-management-configmap
            env:
              - name: SPRING_DATA_MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret-smm
                    key: mongodbUri
              - name: MISTRAL_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: mistral-token-secret-smm
                    key: mistralApiToken
              - name: KEYCLOAK_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: smm-client-secret
                    key: keycloakClientSecret
              - name: KAFKA_BOOTSTRAP_SERVERS
                value: {{ .Values.kafka.bootstrapServers }}
              - name: SCHEMA_REGISTRY_URL
                value: {{ .Values.kafka.schemaRegistryUrl }}
              - name: KAFKA_SASL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: sasl-password-secret
                    key: saslPassword
            resources:
              requests:
                ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage }}
                memory: {{ .Values.resources.requests.memory }}
                cpu: {{ .Values.resources.requests.cpu }}
              limits:
                memory: {{ .Values.resources.limits.memory }}
                cpu: {{ .Values.resources.limits.cpu }}
