apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "springboot-app-movie.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/movies
            pathType: Prefix
            backend:
              service:
                name: {{ include "springboot-app-movie.fullname" . }}
                port:
                  number: 8080