apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mistral-token-secret-smm
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    mistralApiToken: {{ .Values.mistral.encryptedToken }}
  template:
    metadata:
      name: mistral-token-secret-smm
      namespace: {{ .Release.Namespace }}
    type: Opaque