apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app-movie.fullname" . }}
  labels:
    app: {{ include "springboot-app-movie.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "springboot-app-movie.name" . }}
